import { notFound } from 'next/navigation'
import { createServerClient } from '@supabase/ssr'
import { cookies } from 'next/headers'
import { getServiceClient } from '@/lib/supabase'
import { PrintButton } from './PrintButton'

export const dynamic = 'force-dynamic'

// Print-friendly view of a generated Express Cert application.
// Server-rendered so the user can hit Cmd/Ctrl+P → Save as PDF in
// their browser. No client JS needed.

export default async function ExpressCertPrintPage({ params }: { params: Promise<{ id: string }> }) {
  const { id } = await params
  const cookieStore = await cookies()
  const supabase = createServerClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!,
    { cookies: { getAll: () => cookieStore.getAll() } }
  )
  const { data: { user } } = await supabase.auth.getUser()
  if (!user) notFound()

  const db = getServiceClient()
  const { data: app } = await db
    .from('express_cert_applications')
    .select('id, user_id, program, status, generated_pdf_url, generated_at')
    .eq('id', id)
    .maybeSingle()

  if (!app || app.user_id !== user.id || app.status !== 'generated' || !app.generated_pdf_url) {
    notFound()
  }

  const md: string = app.generated_pdf_url
  const programLabel = app.program === 'ctpat' ? 'C-TPAT (US Customs and Border Protection)' : 'OEA (SAT — Operador Económico Autorizado)'

  return (
    <main className="min-h-screen bg-white text-gray-900 print:bg-white">
      <style>{`
        @media print {
          .no-print { display: none !important; }
          @page { margin: 0.6in; }
        }
        .doc h2 { font-size: 1.15rem; font-weight: 700; margin-top: 1.5rem; margin-bottom: 0.5rem; border-bottom: 1px solid #d4d4d8; padding-bottom: 0.25rem; }
        .doc h3 { font-size: 1rem; font-weight: 600; margin-top: 1rem; margin-bottom: 0.4rem; }
        .doc p { margin-bottom: 0.6rem; line-height: 1.55; }
        .doc ul, .doc ol { margin-left: 1.25rem; margin-bottom: 0.6rem; }
        .doc li { line-height: 1.5; margin-bottom: 0.2rem; }
        .doc strong { font-weight: 700; }
      `}</style>
      <div className="max-w-3xl mx-auto px-6 py-8">
        <div className="no-print mb-6 flex items-center justify-between">
          <a href="/express-cert" className="text-sm text-blue-600 hover:underline">← Back</a>
          <PrintButton id={id} />
        </div>
        <header className="mb-8 pb-6 border-b border-gray-300">
          <p className="text-xs text-gray-500 uppercase tracking-wide font-semibold">Cruzar Express Cert</p>
          <h1 className="text-2xl font-bold mt-1">{programLabel}</h1>
          <p className="text-xs text-gray-500 mt-2">Generated: {app.generated_at ? new Date(app.generated_at).toISOString().slice(0, 16).replace('T', ' ') : '—'} UTC</p>
        </header>
        <article className="doc text-sm" dangerouslySetInnerHTML={{ __html: renderMarkdown(md) }} />
        <footer className="mt-12 pt-6 border-t border-gray-300 text-xs text-gray-500">
          This document was generated by Cruzar Express Cert from the
          operator&apos;s submitted answers. Review every section, complete
          any [TODO — provide:] placeholders, and follow the &quot;Next
          Steps&quot; instructions before submitting to the certifying agency.
        </footer>
      </div>
    </main>
  )
}

// Minimal, safe markdown → HTML renderer scoped to the headings,
// paragraphs, lists, and bold formatting our generator produces.
// Avoids pulling marked / remark for one page.
function renderMarkdown(md: string): string {
  const escape = (s: string) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;')
  const lines = md.split(/\r?\n/)
  const out: string[] = []
  let listType: 'ul' | 'ol' | null = null
  const closeList = () => { if (listType) { out.push(`</${listType}>`); listType = null } }
  const inline = (s: string) => escape(s)
    .replace(/\*\*(.+?)\*\*/g, '<strong>$1</strong>')
    .replace(/\*(.+?)\*/g, '<em>$1</em>')
    .replace(/`([^`]+)`/g, '<code>$1</code>')
  for (const raw of lines) {
    const line = raw.trimEnd()
    if (!line.trim()) { closeList(); continue }
    let m: RegExpMatchArray | null
    if ((m = line.match(/^###\s+(.*)$/))) { closeList(); out.push(`<h3>${inline(m[1])}</h3>`); continue }
    if ((m = line.match(/^##\s+(.*)$/)))  { closeList(); out.push(`<h2>${inline(m[1])}</h2>`); continue }
    if ((m = line.match(/^#\s+(.*)$/)))   { closeList(); out.push(`<h2>${inline(m[1])}</h2>`); continue }
    if ((m = line.match(/^[-*]\s+(.*)$/))) {
      if (listType !== 'ul') { closeList(); out.push('<ul>'); listType = 'ul' }
      out.push(`<li>${inline(m[1])}</li>`); continue
    }
    if ((m = line.match(/^\d+\.\s+(.*)$/))) {
      if (listType !== 'ol') { closeList(); out.push('<ol>'); listType = 'ol' }
      out.push(`<li>${inline(m[1])}</li>`); continue
    }
    closeList()
    out.push(`<p>${inline(line)}</p>`)
  }
  closeList()
  return out.join('\n')
}
