'use client'

export type Lang = 'en' | 'es'

export const translations = {
  en: {
    appName: 'Cruzar',
    subtitle: 'Live border wait times',
    allRegions: '📍 All Regions',
    enteringUS: '🇺🇸 Entering the US',
    enteringMexico: '🇲🇽 Entering Mexico',
    updatedJustNow: 'Updated just now',
    updatedAgo: (m: number) => `Updated ${m}m ago`,
    list: 'List',
    map: 'Map',
    tapDot: 'Tap a dot to see details',
    noData: 'No port data available.',
    car: 'Car',
    sentri: 'SENTRI',
    walk: 'Walk',
    truck: 'Truck',
    carsAhead: (n: number) => `~${n} cars`,
    closed: 'Closed',
    signUpFree: 'Sign Up Free',
    localBusiness: 'Advertise',
    me: 'Me',
    underMin: 'Under 20 min',
    midMin: '20–45 min',
    overMin: '45+ min',
    mexicoSideTitle: 'Mexico-side wait times',
    mexicoSideDesc: 'No official data exists for crossing into Mexico — Mexico doesn\'t publish wait times publicly. Wait times entering Mexico are typically under 5 minutes.',
    communityTip: '💡 Community tip',
    communityTipDesc: 'Returning to Mexico is usually quick — Mexican customs rarely causes delays. Busy periods are Friday afternoons and weekends when US-side shoppers return.',
    createAccount: 'Create a free account',
    toSeeLocalDeals: 'to see local deals instead of ads',
    // Report form
    reportTitle: 'What\'s happening at this crossing?',
    reportSubmit: 'Submit Report',
    reportSubmitting: 'Submitting...',
    reportDone: 'Report submitted — thanks!',
    reportPlaceholder: 'Optional details (lane, cause, etc.)',
    reportLong: 'Long Delay',
    reportInspection: 'Inspection',
    reportAccident: 'Accident',
    reportClear: 'Moving Fast',
    reportOther: 'Other',
    // Just Crossed
    justCrossedTitle: (port: string) => `Just crossed at ${port}?`,
    justCrossedSub: 'Help others + earn points',
    justCrossedFast: 'Fast',
    justCrossedNormal: 'Normal',
    justCrossedSlow: 'Slow',
    justCrossedMinutes: 'Actual wait in minutes (optional)',
    justCrossedSubmit: 'Submit Report',
    justCrossedThanks: 'Thanks! ¡Gracias!',
    justCrossedHelping: 'You\'re helping fellow crossers.',
    // Nav/UI
    allCrossings: 'All crossings',
    recentReports: 'Recent community reports',
    noReports: 'No reports in the last 24 hours.',
    beFirst: 'Be the first to report!',
    anonymous: 'Anonymous',
    justNow: 'just now',
    ago: (m: number) => `${m}m ago`,
    hoursAgo: (h: number) => `${h}h ago`,
    plannerBannerTitle: '🔮 Smart Crossing Planner',
    plannerBannerSub: 'See the best time to cross — any port, any day',
    plannerTry: 'Try it →',
    // Lane labels
    laneCar: 'Car',
    laneSentri: 'SENTRI',
    laneWalk: 'Walk',
    laneTruck: 'Truck',
    // Wait states
    noWaitLowTraffic: 'No wait · Low traffic',
    lessThanMin: '< 1 min',
    // PortList legend
    legendNoWait: 'No / low wait',
    // Services
    servicesLink: 'Services in MX →',
    // Login
    loginSubtitle: 'Sign in to your account',
    continueWithGoogle: 'Continue with Google',
    continueWithPhone: 'Continue with Phone',
    emailLabel: 'Email',
    passwordLabel: 'Password',
    forgotPassword: 'Forgot password?',
    signingIn: 'Signing in...',
    signInBtn: 'Sign In',
    noAccount: 'No account?',
    signUpFreeLink: 'Sign up free',
    backToMap: '← Back to map',
    // Signup
    signupSubtitle: 'Create your free account',
    signUpWithGoogle: 'Sign up with Google',
    signUpWithPhone: 'Sign up with Phone',
    iAmA: 'I am a...',
    roleDriver: '🚛 Driver / Operator',
    roleDriverDesc: 'I cross the border for work or daily commute',
    roleFleetMgr: '🏢 Fleet Manager',
    roleFleetMgrDesc: 'I manage multiple drivers and vehicles',
    companyNameLabel: 'Company Name',
    companyNamePlaceholder: 'Your company name',
    creatingAccount: 'Creating account...',
    createAccountBtn: 'Create Account',
    alreadyHaveAccount: 'Already have an account?',
    signInLink: 'Sign in',
    passwordMinChars: 'Min 6 characters',
    // Account / Settings
    settingsTitle: 'Settings',
    signOutBtn: 'Sign out',
    businessPortalDesc: 'Drivers · Dispatch · Loads · Cost Calculator',
    subscriptionSection: 'Subscription',
    statusLabel: 'Status:',
    renewsLabel: 'Renews',
    manageBilling: 'Manage Billing',
    openingPortal: 'Opening...',
    upgradeToPro: 'Upgrade to Pro →',
    communityStats: 'Community Stats',
    leaderboardLink: 'Leaderboard',
    pointsLabel: 'Points',
    reportsLabel: 'Reports',
    profileSection: 'Profile',
    displayNameLabel: 'Display name',
    displayNameHint: '(shown on your reports)',
    fullNameLabel: 'Full name',
    companyLabel: 'Company / Employer',
    bioLabel: 'Short bio',
    bioHint: '(shows on your reports)',
    roleLabel: 'Role',
    saveProfile: 'Save Profile',
    savingProfile: 'Saving...',
    profileSaved: 'Saved!',
    accountSection: 'Account',
    viewPricingPlans: 'View pricing & plans →',
    signOutCruza: 'Sign out of Cruzar',
    // Dashboard
    dashboardTitle: 'My Account',
    savedTab: '⭐ Saved',
    alertsTab: '🔔 Alerts',
    routeTab: '🗺️ Route',
    upgradeLink: 'Upgrade →',
    noSavedCrossings: 'No saved crossings yet',
    noSavedHint: 'Tap ⭐ on any crossing to save it here',
    browseCrossingsBtn: 'Browse Crossings',
    directionsBtn: 'Directions',
    removeBtn: 'Remove',
    alertsProLocked: 'Alerts are a Pro feature',
    alertsProDesc: 'Get notified the moment your crossing drops below your target wait time.',
    upgradeProBtn: 'Upgrade to Pro — $2.99/mo',
    trialNote: '7-day free trial, cancel anytime',
    addAlertTitle: 'Add Alert',
    selectCrossing: 'Select a crossing...',
    notifyWhenUnder: 'Notify when under',
    smsPhonePlaceholder: 'SMS phone (optional) e.g. +15551234567',
    addAlertBtn: 'Add Alert',
    noAlertsYet: 'No alerts set up yet.',
    routeProLocked: 'Route Optimizer is a Pro feature',
    routeProDesc: 'Find the fastest crossing near you based on live wait times.',
    originCityLabel: 'Your origin city (US side)',
    findBestBtn: '🗺️ Find Best Crossing Now',
    findingRoute: 'Finding best route...',
    bestOption: '✅ BEST OPTION — tap to view',
    alternativeN: (n: number) => `Alternative #${n} — tap to view`,
    welcomePro: 'Welcome to Pro! 🎉',
    welcomeProDesc: 'You now have access to wait time alerts and all Pro features.',
    // Pricing
    pricingTitle: 'Simple, transparent pricing',
    pricingSubtitle: 'Start free. Upgrade when you need more.',
    mostPopular: 'Most Popular',
    forFreight: 'For Freight & Logistics',
    freePeriod: 'forever',
    currentPlanLabel: 'Current Plan',
    roiTitle: '💡 How much is border wait time costing you?',
    advertiseCTA: 'Own a local business near the border?',
    advertiseDesc: 'Advertise to thousands of daily cross-border commuters. Starting at $49/month.',
    advertiseBtn: 'Advertise Your Business →',
    // Port detail
    currentWaitTimes: 'Current Wait Times',
    passengerVehicle: 'Passenger Vehicle',
    sentriReadyLane: 'SENTRI / Ready Lane',
    pedestrianLabel: 'Pedestrian',
    commercialTruck: 'Commercial / Truck',
    last24Hours: 'Last 24 Hours',
    notEnoughData: 'Not enough data yet. Check back after a few hours.',
    historicalPatterns: 'Historical Patterns – Next 24 Hours',
    basedOnHistorical: 'Based on historical patterns for this crossing',
    historicalWaitPredictions: '🔮 Historical Wait Patterns',
    seePredictions: 'See predicted wait times for the next 24 hours. Pro feature.',
    bestTimesToday: 'Best Times Today (based on history)',
    driverReports: 'Driver Reports',
    submitReportLabel: 'Submit a Report',
    alertNudge: '🔔 Get alerts when wait drops',
    tryProFree: 'Try Pro Free for 7 Days',
    upgradeForAlerts: 'Upgrade to Pro for $2.99/mo',
    // Leaderboard
    leaderboardTitle: 'Community Leaderboard',
    leaderboardSubtitle: 'Top contributors helping crossers save time',
    leaderboardBadges: 'Badges',
    leaderboardHowToEarn: 'How to earn points',
    leaderboardNoReports: 'No reports yet.',
    leaderboardBeFirst: 'Be the first to report and top the board!',
    leaderboardReports: (n: number) => `${n} reports submitted`,
    leaderboardBottom: 'Submit a crossing report to start earning points →',
    leaderboardViewCrossings: 'View crossings',
    // Pro upsell banner
    proUpsellTitle: '🔔 Get alerts when wait times drop',
    proUpsellSub: 'Pro users get instant notifications — $2.99/mo',
    proUpsellBtn: 'Try Pro free →',
  },
  es: {
    appName: 'Cruzar',
    subtitle: 'Tiempos de espera en la frontera en vivo',
    allRegions: '📍 Todas las regiones',
    enteringUS: '🇺🇸 Entrando a EE.UU.',
    enteringMexico: '🇲🇽 Entrando a México',
    updatedJustNow: 'Actualizado ahora mismo',
    updatedAgo: (m: number) => `Actualizado hace ${m} min`,
    list: 'Lista',
    map: 'Mapa',
    tapDot: 'Toca un punto para ver detalles',
    noData: 'No hay datos disponibles.',
    car: 'Auto',
    sentri: 'SENTRI',
    walk: 'Peatón',
    truck: 'Camión',
    carsAhead: (n: number) => `~${n} autos`,
    closed: 'Cerrado',
    signUpFree: 'Regístrate Gratis',
    localBusiness: 'Publicidad',
    me: 'Yo',
    underMin: 'Menos de 20 min',
    midMin: '20–45 min',
    overMin: 'Más de 45 min',
    mexicoSideTitle: 'Tiempos del lado mexicano',
    mexicoSideDesc: 'No existen datos oficiales para cruzar a México. Entrar a México generalmente toma menos de 5 minutos.',
    communityTip: '💡 Consejo de la comunidad',
    communityTipDesc: 'Regresar a México suele ser rápido. Los períodos más ocupados son los viernes por la tarde y los fines de semana.',
    createAccount: 'Crea una cuenta gratis',
    toSeeLocalDeals: 'para ver ofertas locales en vez de anuncios',
    // Report form
    reportTitle: '¿Qué está pasando en este cruce?',
    reportSubmit: 'Enviar Reporte',
    reportSubmitting: 'Enviando...',
    reportDone: '¡Reporte enviado — gracias!',
    reportPlaceholder: 'Detalles opcionales (carril, causa, etc.)',
    reportLong: 'Demora larga',
    reportInspection: 'Inspección',
    reportAccident: 'Accidente',
    reportClear: 'Fluye rápido',
    reportOther: 'Otro',
    // Just Crossed
    justCrossedTitle: (port: string) => `¿Acabas de cruzar en ${port}?`,
    justCrossedSub: 'Ayuda a otros + gana puntos',
    justCrossedFast: 'Rápido',
    justCrossedNormal: 'Normal',
    justCrossedSlow: 'Lento',
    justCrossedMinutes: 'Tiempo real de espera en minutos (opcional)',
    justCrossedSubmit: 'Enviar Reporte',
    justCrossedThanks: '¡Gracias! Thanks!',
    justCrossedHelping: 'Estás ayudando a otros cruzantes.',
    // Nav/UI
    allCrossings: 'Todos los cruces',
    recentReports: 'Reportes recientes de la comunidad',
    noReports: 'Sin reportes en las últimas 24 horas.',
    beFirst: '¡Sé el primero en reportar!',
    anonymous: 'Anónimo',
    justNow: 'justo ahora',
    ago: (m: number) => `hace ${m} min`,
    hoursAgo: (h: number) => `hace ${h}h`,
    plannerBannerTitle: '🔮 Planificador Inteligente',
    plannerBannerSub: 'Encuentra el mejor horario para cruzar',
    plannerTry: 'Probar →',
    // Lane labels
    laneCar: 'Auto',
    laneSentri: 'SENTRI',
    laneWalk: 'Peatón',
    laneTruck: 'Camión',
    // Wait states
    noWaitLowTraffic: 'Sin espera · Poco tráfico',
    lessThanMin: '< 1 min',
    // PortList legend
    legendNoWait: 'Sin espera',
    // Services
    servicesLink: 'Servicios en MX →',
    // Login
    loginSubtitle: 'Inicia sesión en tu cuenta',
    continueWithGoogle: 'Continuar con Google',
    continueWithPhone: 'Continuar con Teléfono',
    emailLabel: 'Correo electrónico',
    passwordLabel: 'Contraseña',
    forgotPassword: '¿Olvidaste tu contraseña?',
    signingIn: 'Iniciando sesión...',
    signInBtn: 'Iniciar Sesión',
    noAccount: '¿Sin cuenta?',
    signUpFreeLink: 'Regístrate gratis',
    backToMap: '← Volver al mapa',
    // Signup
    signupSubtitle: 'Crea tu cuenta gratis',
    signUpWithGoogle: 'Regístrate con Google',
    signUpWithPhone: 'Regístrate con Teléfono',
    iAmA: 'Soy...',
    roleDriver: '🚛 Chofer / Operador',
    roleDriverDesc: 'Cruzo la frontera por trabajo o mi rutina diaria',
    roleFleetMgr: '🏢 Gerente de Flota',
    roleFleetMgrDesc: 'Administro varios choferes y vehículos',
    companyNameLabel: 'Nombre de Empresa',
    companyNamePlaceholder: 'Nombre de tu empresa',
    creatingAccount: 'Creando cuenta...',
    createAccountBtn: 'Crear Cuenta',
    alreadyHaveAccount: '¿Ya tienes cuenta?',
    signInLink: 'Inicia sesión',
    passwordMinChars: 'Mín. 6 caracteres',
    // Account / Settings
    settingsTitle: 'Configuración',
    signOutBtn: 'Cerrar sesión',
    businessPortalDesc: 'Choferes · Despacho · Cargas · Calculadora de Costos',
    subscriptionSection: 'Suscripción',
    statusLabel: 'Estado:',
    renewsLabel: 'Renueva',
    manageBilling: 'Administrar Facturación',
    openingPortal: 'Abriendo...',
    upgradeToPro: 'Actualizar a Pro →',
    communityStats: 'Estadísticas de Comunidad',
    leaderboardLink: 'Tabla de Líderes',
    pointsLabel: 'Puntos',
    reportsLabel: 'Reportes',
    profileSection: 'Perfil',
    displayNameLabel: 'Nombre de usuario',
    displayNameHint: '(visible en tus reportes)',
    fullNameLabel: 'Nombre completo',
    companyLabel: 'Empresa / Empleador',
    bioLabel: 'Bio corta',
    bioHint: '(visible en tus reportes)',
    roleLabel: 'Rol',
    saveProfile: 'Guardar Perfil',
    savingProfile: 'Guardando...',
    profileSaved: '¡Guardado!',
    accountSection: 'Cuenta',
    viewPricingPlans: 'Ver precios y planes →',
    signOutCruza: 'Cerrar sesión de Cruzar',
    // Dashboard
    dashboardTitle: 'Mi Cuenta',
    savedTab: '⭐ Guardados',
    alertsTab: '🔔 Alertas',
    routeTab: '🗺️ Ruta',
    upgradeLink: 'Actualizar →',
    noSavedCrossings: 'Sin cruces guardados aún',
    noSavedHint: 'Toca ⭐ en cualquier cruce para guardarlo aquí',
    browseCrossingsBtn: 'Ver Cruces',
    directionsBtn: 'Cómo llegar',
    removeBtn: 'Eliminar',
    alertsProLocked: 'Las alertas son una función Pro',
    alertsProDesc: 'Recibe una notificación cuando tu cruce baje del tiempo de espera deseado.',
    upgradeProBtn: 'Actualizar a Pro — $2.99/mes',
    trialNote: 'Prueba gratuita de 7 días, cancela cuando quieras',
    addAlertTitle: 'Agregar Alerta',
    selectCrossing: 'Selecciona un cruce...',
    notifyWhenUnder: 'Notificar cuando sea menos de',
    smsPhonePlaceholder: 'Teléfono SMS (opcional) ej. +15551234567',
    addAlertBtn: 'Agregar Alerta',
    noAlertsYet: 'Sin alertas configuradas aún.',
    routeProLocked: 'El Optimizador de Ruta es una función Pro',
    routeProDesc: 'Encuentra el cruce más rápido cerca de ti según los tiempos en vivo.',
    originCityLabel: 'Tu ciudad de origen (lado EE.UU.)',
    findBestBtn: '🗺️ Encontrar Mejor Cruce Ahora',
    findingRoute: 'Buscando mejor ruta...',
    bestOption: '✅ MEJOR OPCIÓN — toca para ver',
    alternativeN: (n: number) => `Alternativa #${n} — toca para ver`,
    welcomePro: '¡Bienvenido a Pro! 🎉',
    welcomeProDesc: 'Ahora tienes acceso a alertas de espera y todas las funciones Pro.',
    // Pricing
    pricingTitle: 'Precios simples y transparentes',
    pricingSubtitle: 'Comienza gratis. Actualiza cuando necesites más.',
    mostPopular: 'Más Popular',
    forFreight: 'Para Fletes y Logística',
    freePeriod: 'para siempre',
    currentPlanLabel: 'Plan Actual',
    roiTitle: '💡 ¿Cuánto te está costando el tiempo de espera en la frontera?',
    advertiseCTA: '¿Tienes un negocio local cerca de la frontera?',
    advertiseDesc: 'Anúnciate a miles de cruzantes diarios. Desde $49/mes.',
    advertiseBtn: 'Anuncia Tu Negocio →',
    // Port detail
    currentWaitTimes: 'Tiempos de Espera Actuales',
    passengerVehicle: 'Vehículo de Pasajeros',
    sentriReadyLane: 'SENTRI / Carril Rápido',
    pedestrianLabel: 'Peatón',
    commercialTruck: 'Comercial / Camión',
    last24Hours: 'Últimas 24 Horas',
    notEnoughData: 'Datos insuficientes aún. Vuelve en unas horas.',
    historicalPatterns: 'Patrones Históricos – Próximas 24 Horas',
    basedOnHistorical: 'Basado en patrones históricos de este cruce',
    historicalWaitPredictions: '🔮 Patrones Históricos de Espera',
    seePredictions: 'Ve los tiempos estimados para las próximas 24 horas. Función Pro.',
    bestTimesToday: 'Mejores Horarios Hoy (basado en historial)',
    driverReports: 'Reportes de Choferes',
    submitReportLabel: 'Enviar un Reporte',
    alertNudge: '🔔 Recibe alertas cuando baje la espera',
    tryProFree: 'Prueba Pro Gratis 7 Días',
    upgradeForAlerts: 'Actualiza a Pro por $2.99/mes',
    // Leaderboard
    leaderboardTitle: 'Tabla de Líderes',
    leaderboardSubtitle: 'Los que más ayudan a la comunidad cruzante',
    leaderboardBadges: 'Insignias',
    leaderboardHowToEarn: 'Cómo ganar puntos',
    leaderboardNoReports: 'Sin reportes todavía.',
    leaderboardBeFirst: '¡Sé el primero en reportar y encabeza la tabla!',
    leaderboardReports: (n: number) => `${n} reportes enviados`,
    leaderboardBottom: 'Envía un reporte para empezar a ganar puntos →',
    leaderboardViewCrossings: 'Ver cruces',
    // Pro upsell banner
    proUpsellTitle: '🔔 Recibe alertas cuando baje la espera',
    proUpsellSub: 'Los usuarios Pro reciben notificaciones al instante — $2.99/mes',
    proUpsellBtn: 'Prueba Pro gratis →',
  },
}

export type T = typeof translations.en
